### PR TITLE
Retry connection

### LINKED ISSUE #1: Retry connection
Implements retry connections

### PR DESCRIPTION
**Pull request by DBX12**
Fixes #1 

## Proposed Changes

  - Checkout the tests and adapt as needed (I don't know Mockery, I'm sorry)
  -  Needs checking how to proceed with the $client object and setClient method as we need to insert the handler stack. I created a new Client with the configuration of the old one merged with my definitions of the handler stack.

### CODE REVIEW

**Comment by marcus-campos** [comment]
Whoops, your pull request was not accepted by the 3 validations and is conflicting with the Rest.php file. Could you check and fix it?

**Comment by DBX12** [comment]
I will look into it, but I guess codeclimate is pretty strict about the maximum of lines in a method.

**Comment by DBX12** [comment]
So fixed the one issue, created another one. First codeclimate tells me, the function is too long. No big deal, I refactor it into a separate function. Now I have too many functions for the class Rest and the `getRetryDecider` function is too complex. Do you have any idea how to make the function less complex? It's not too complex in my opinion, maybe it dislikes the `&& $returnValue === null` part of the if statements but it's necessary as it does not allow me to return early.

**Comment by DBX12** [comment]
Still standing by my point with the codeclimate issues. The last (new) issue `Avoid unused local variables such as '$request'.` in line 283 is not an issue as `getRetryDecider()` returns a function with for the RetryMiddleware. And this so called decider-function has a signature with two required parameters and two optional parameters.
@marcus-campos please look into the codeclimate tests and give me some hints on fixing them.
Cheers,
DBX12

**Pull request merged**
